notifications:
  email:
    on_success: never 
    on_failure: never 

language: php
php:
  - nightly
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  
before_script:
  - echo Start travis
  - echo Current dir is `pwd`
  - echo Home dir is `echo ~`
  - composer global require "squizlabs/php_codesniffer=*"
  - phpenv rehash
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - phpcs -i
  - phpcs --standard=PEAR /home/travis/build/thulin82/arsenal_webscrape
  - phpunit
  
after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover